baseURL: https://papermod-dibakar.pages.dev/
languageCode: en-us
title: dibakar
theme: ['PaperMod']

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ['blogs', 'papermod']

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: dibakar
  description: personal blogs of Dibakar, a SWE focused on server side
  keywords: [Blog, Portfolio, PaperMod]
  # author: dibakar
  # author: ["Me", "You"] # multiple authors
  # images: ['']
  DateFormat: '2 January 2006'
  defaultTheme: dark # auto, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: true
    title: 'dibakar sutra dhar' # optional default will be site title
    subtitle: 'i design softwares for living'
    imageUrl: 'images/profile.png' # optional
    imageTitle: "dibakar's headshot" # optional
    imageWidth: 140 # custom size
    imageHeight: 140 # custom size
    buttons:
      - name: whoami
        url: '/whoami'
      - name: archives
        url: '/archives/'
      - name: calendly
        url: 'https://calendly.com/dibakarsutradhar/take-a-coffee-break'

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B, it's Dibakar"
  #   Content: >
  #     I'm a **Software Engineer**, and I write things on the server side.

  #     - I mainly use Node.js with JS/TS to write stuffs. However, I've been writing Python with Django for over a year now due to work.

  #     - Recently, I'm learning Rust and Dev Ops.

  socialIcons:
    - name: github
      url: 'https://github.com/dibakarsutradhar'
    - name: x
      url: 'https://x.com/d1bakar'
    - name: linkedin
      url: 'https://linkedin.com/in/dibakarsutradhar'
    - name: email
      url: 'mailto:iamdibakardipu@gmail.com'
    - name: medium
      url: 'https://medium.com/@imdibakar'
    - name: telegram
      url: 'https://t.me/imghostly'

  ShareButtons: ['linkedin', 'x', 'reddit', 'facebook', 'whatsapp', 'telegram']

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ['title', 'permalink', 'summary', 'content']

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

menu:
  main:
    - identifier: blog
      name: blogs
      url: /blogs/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 25
    - identifier: portfolio
      name: chainrunner
      # url: https://example.org
      weight: 30
