baseURL: https://papermod-dibakar.pages.dev/
languageCode: en-us
title: Dibakar Sutra Dhar
theme: ['PaperMod']

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# mainsections: ['posts', 'papermod']

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Dibakar Sutra Dhar
  description: Personal blogs of Dibakar, a SWE focused on server side
  keywords: [Blog, Portfolio, PaperMod]
  author: dibakarsutradhar
  # author: ["Me", "You"] # multiple authors
  # images: ['<link or path of image for opengraph, twitter-cards>']
  DateFormat: '2 January 2006'
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B, it's Dibakar"
    Content: >
      I'm a **Software Engineer**, and I write things on the server side.

      - I mainly use Node.js with JS/TS to write stuffs. However, I've been writing Python with Django for over a year now due to work.

      - Recently, I'm learning Rust and Dev Ops.

  socialIcons:
    - name: github
      url: 'https://github.com/dibakarsutradhar'
    - name: Discord
      url: 'https://discord.gg/imdibakar'
    - name: X
      url: 'https://x.com/d1bakar'
    - name: LinkedIn
      url: 'https://linkedin.com/in/dibakarsutradhar'
    # - name: KoFi
    #   title: Buy me a Ko-Fi :)
    #   url: 'https://ko-fi.com/username'

menu:
  main:
    - identifier: blog
      name: blogs
      url: /blogs/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: portfolio
      name: chainrunner
      # url: https://example.org
      weight: 30
